#!/bin/bash
# @parseArger-begin
# @parseArger-help "I send an SOS to the world" --option "help" --short-option "h"
# @parseArger-set export PARSEARGER_ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")";pwd -P);
export PARSEARGER_ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")";pwd -P);
# @parseArger-leftovers leftovers
# @parseArger-declarations
# @parseArger pos target "what to do" --one-of "parse" --one-of "generate" --subcommand
# @parseArger opt output "create file with command output at value"
# @parseArger flag prepend "add output on top of file"
# @parseArger-declarations-end

# @parseArger-parsing
die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options=''
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# POSITIONALS ARGUMENTS
_positionals=();
_arg_target="";
_one_of_arg_target=("parse" "generate" );
# OPTIONALS ARGUMENTS
_arg_output=
# FLAGS
_arg_prepend="off"
# LEFTOVERS
_arg_leftovers=()


print_help()
{
	echo -e "I send an SOS to the world:"
	echo -e "	target: what to do [one of 'parse' 'generate']"
	echo -e "	--output <output>: create file with command output at value"
	echo -e "	--prepend|--no-prepend: add output on top of file"
	echo -e "Usage :
	$0 <target> [--output <value>] [--[no-]prepend]"
}

parse_commandline()
{
	_positionals_count=0
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			--output)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_output="$2"
				shift
				;;
			--output=*)
				_arg_output="${_key##--output=}"
				;;
			
			--no-prepend|--prepend)
				_arg_prepend="on"
				test "${1:0:5}" = "--no-" && _arg_prepend="off"
				;;
			-h|--help)
				print_help;
				exit 0;
				;;
			-h*)
				print_help;
				exit 0;
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="target"
	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
}


assign_positional_args()
{
	local _positional_name _shift_for=$1;
	_positional_names="_arg_target ";
	_leftovers_count=$((${#_positionals[@]} - 1))
	for ((ii = 0; ii < _leftovers_count; ii++));do
		_positional_names="$_positional_names _arg_leftovers[$((ii + 0))]";
	done

	shift "$_shift_for"
	for _positional_name in ${_positional_names};do
		test $# -gt 0 || break;
		if ! [[ "$_positional_name" =~ "_arg_leftovers" ]];then
			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
		fi
eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
		shift;
	done
}

print_debug()
{
	print_help
	# shellcheck disable=SC2145
	echo "DEBUG: $0 $@";
	
	echo -e "\ttarget: ${_arg_target}";
	echo -e "\toutput: ${_arg_output | sed 's/-/_/g'}";
	echo -e "\tprepend: ${_arg_prepend | sed 's/-/_/g'}";
	echo -e "\tleftovers: ${_arg_leftovers[*]}";

}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# @parseArger-parsing-end
# print_debug "$@"
# @parseArger-end

if [ "$_arg_output" == "" ]; then
	"$PARSEARGER_ROOT_DIR/bin/$_arg_target" "${_arg_leftovers[@]}";
else
	output="$("$PARSEARGER_ROOT_DIR/bin/$_arg_target" "${_arg_leftovers[@]}")";
	
	if [[ -f "$_arg_output" ]]; then
		if [ "$_arg_prepend" == "on" ]; then
			output+=$(cat "$_arg_output");
		else
			output=$(cat "$_arg_output")$output;
		fi	
	fi

	echo -e "${output}" > "$_arg_output";
	chmod +x "$_arg_output";
fi
