#!/bin/bash

__script_bin="./__bin_name__";
__script_exec=("$__script_bin");

function test___program_name___exists () {
  assert_file_exists "$__script_bin";
}

function test___program_name___help () {  
  assert_exit_code "0" "$("${__script_exec[@]}" --help 2>&1)";
  assert_exit_code "0" "$("${__script_exec[@]}" -h 2>&1)";  
}

# function test___program_name___version () {
#   assert_exit_code "0" "$("${__script_exec[@]}" --version 2>&1)";
#   assert_exit_code "0" "$("${__script_exec[@]}" -v 2>&1)";
# }
